
components:
  schemas:
    GreetingMessage:
      properties:
        message:
          type: string
      type: object
info:
  title: Generated API
  version: '1.0'
openapi: 3.0.3
paths:
  /myapp/dummyEndpoint:
    get:
      description: Dummy endpoint from META-INF/openapi.yam file
      responses:
        default:
          description: Nothing interesting to respond
  /myapp/greet:
    get:
      description: Greets the user generically
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetingMessage'
          description: Simple JSON containing the greeting
      summary: Returns a generic greeting
  /myapp/greet/greeting:
    put:
      description: Permits the client to set the prefix part of the greeting ("Hello")
      requestBody:
        content:
          application/json:
            examples:
              greeting:
                summary: Example greeting message to update
                value: New greeting message
            schema:
              $ref: '#/components/schemas/GreetingMessage'
        description: Conveys the new greeting prefix to use in building greetings
      responses:
        '200':
          description: OK
      summary: Set the greeting prefix
  /myapp/greet/{name}:
    get:
      parameters:
        -
          in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GreetingMessage'
          description: Simple JSON containing the greeting
      summary: Returns a personalized greeting